#aSpYJAW8Nxhk1FbgsJacfzkry:0SHnU8QvaALVhv78Rv8WQKw8VcVSVCYih973nFRjTmChPbA7xs 
# @name getBearerToken
POST https://api.twitter.com/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic YVNwWUpBVzhOeGhrMUZiZ3NKYWNmemtyeTowU0huVThRdmFBTFZodjc4UnY4V1FLdzhWY1ZTVkNZaWg5NzNuRlJqVG1DaFBiQTd4cw==

grant_type=client_credentials

@accessToken = {{getBearerToken.response.body.access_token}}
###

@keyword = bitcoin
GET  https://api.twitter.com/1.1/search/tweets.json?q={{keyword}}&result_type=popular&count=2 HTTP/1.1
Authorization: Bearer {{accessToken}}
###

GET http://localhost:7071/api/tweets/Samsung

###

GET http://company-search.azurewebsites.net/api/tweets/Nokia


###

GET https://www.alphavantage.co/query?function=SYMBOL_SEARCH&keywords=apple&apikey=NMJ4EQ7YJJ272PQU
#NMJ4EQ7YJJ272PQU

###

GET https://www.alphavantage.co/query?function=TIME_SERIES_MONTHLY&symbol=AAPL&apikey=NMJ4EQ7YJJ272PQU